DIRECTORIES = {
    "HTML": [".html5", ".html", ".htm", ".xhtml"],
    "MARKUP": [".md"],
    "IMAGES": [
        ".jpeg",
        ".jpg",
        ".tiff",
        ".gif",
        ".bmp",
        ".png",
        ".bpg",
        ".svg",
        ".heif",
        ".psd",
    ],
    "VIDEOS": [
        ".avi",
        ".flv",
        ".wmv",
        ".mov",
        ".mp4",
        ".webm",
        ".vob",
        ".mng",
        ".qt",
        ".mpg",
        ".mpeg",
        ".3gp",
        ".mkv",
    ],
    "DOCUMENTS": [
        ".oxps",
        ".epub",
        ".pages",
        ".docx",
        ".doc",
        ".fdf",
        ".ods",
        ".odt",
        ".pwi",
        ".xsn",
        ".xps",
        ".dotx",
        ".docm",
        ".dox",
        ".rvg",
        ".rtf",
        ".rtfd",
        ".wpd",
        ".xls",
        ".xlsx",
        ".ppt",
        ".pptx",
        ".md",
        ".pages",
        ".numbers",
    ],
    "ARCHIVES": [
        ".a",
        ".ar",
        ".arh",
        ".tar",
        ".tar.bz2",
        ".tar.gz",
        ".cpio",
        ".tar",
        ".gz",
        ".rz",
        ".7z",
        ".rar",
        ".xar",
        ".zip",
        ".xz",
        ".pkg",
        ".deb",
        ".rpm",
    ],
    "DISKIMAGE": [".iso", ".img", ".vcd", ".dmg"],
    "AUDIO": [
        ".aac",
        ".aa",
        ".aac",
        ".dvf",
        ".flac",
        ".m4a",
        ".m4b",
        ".m4p",
        ".mid",
        ".midi",
        ".mp3",
        ".msv",
        ".ogg",
        "oga",
        ".raw",
        ".vox",
        ".wav",
        ".wma",
    ],
    "PLAINTEXT": [".txt", ".in", ".out", ".csv", ".log"],
    "POWERSHELL": [".ps1", ".psm1", ".psd1"],
    "PDF": [".pdf"],
    "PYTHON": [".py", ".pyi", ".pyc"],
    "EXECUTABLE": [".exe", ".run"],
    "SHELL": [".sh"],
    "DATABASE": [".db", ".sql", ".sqlite"],
    "C#": [".cs"],
    "C++": [".cpp"],
    "C": [".c"],
    "GO": [".go"],
    "YAML": [".yaml"],
    "JSON": [".json"],
    "ASP Classic": [".asp"],
    "ASP_NET": [".aspx", ".axd", ".asx", ".asmx", ".ashx"],
    "CSS": [".css"],
    "Coldfusion": [".cfm"],
    "Erlang": [".yaws"],
    "Flash": [".swf"],
    "Java": [".jar", ".java", ".jsp", ".jspx", ".wss", ".do", ".action", ".class"],
    "Kotlin": [".kt", ".kts", ".ktm"],
    "JavaScript": [".js"],
    "TypeScript": [".ts"],
    "Rust": [".rs", ".rlib"],
    "Toml": [".toml"],
    "Travis": [".travis"],
    "Perl": [".pl"],
    "PHP": [".php", ".php4", ".php3", ".phtml"],
    "Ruby": [".rb", ".rhtml"],
    "SSI": [".shtml"],
    "SWIFT": [".swift"],
    "XML": [".xml", ".fxml", ".rss", ".svg"],
    "APPS": [".app", ".ipa", ".apk"],
    "LINKS": [".webloc", ".lnk"],
    "FONTS": [".fnt", ".fon", ".otf", ".ttf"],
}
